spring.application.name=rate-limiter-service

# token-bucket
ratelimit.token-bucket.capacity=10
ratelimit.token-bucket.refill-rate-per-second=5

#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=rate-limiter-redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
